project_id = "lwxzworimcgdfavgzzjw"

[functions.book-search]
verify_jwt = false

[functions.search-videos]
verify_jwt = false

[functions.search-podcasts]
verify_jwt = false

[functions.author-info]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false
